Db
tagirahmad/test_guru pull request #6
Opened 2021-07-09 12:02 UTC by tagirahmad

2021-07-10 13:52 UTC, BubuntuClu requested changes

2021-07-10 13:52 UTC, BubuntuClu commented on db/migrate/20210710094749_add_user_to_test.rb
> +    add_reference :tests, :user, null: false, foreign_key: true
ты реализовал связь один-ко-многим, а надо многие-ко-многим. каждый пользователь может проходить много тестов, и каждый тест могут проходить много пользователей. в твоей структуре таблиц сейчас нельзя это сделать, надо добавить промежуточную таблицу для реализации этой связи

2021-07-10 13:52 UTC, BubuntuClu commented on db/seeds.rb
> +  Test.create(title: "Test #{index + 1}", level: index, category_id: Category.pluck(:id).sample, user_id: User.pluck(:id).sample)
ты только что создал категории и положил их в таблицу. зачем `Category.pluck(:id)` за ним о5 лезть в таблицу, если можно сохранить в массив созданные объекты и их потом использовать. лишняя работа для БД

2021-07-10 17:32 UTC, BubuntuClu commented on db/migrate/20210710142607_create_join_table_users_tests.rb
> +      t.index :user_id
внешние ключи еще добавить надо. `t.references :..., foreign_key: true`

2021-07-10 17:32 UTC, BubuntuClu requested changes

2021-07-10 17:32 UTC, BubuntuClu commented on app/models/user.rb
> +    Test.where(level: level, user_id: self.id)
метод все еще работает неправильно. новая таблица тут никак не участвует, а должна

2021-07-11 04:16 UTC, BubuntuClu requested changes

2021-07-11 04:16 UTC, BubuntuClu commented on app/models/user.rb
> +    Test.joins(:users).where(level: level, users: self.id)
ты проверил в консоле этот код? мне кажется, он не работает

2021-07-11 04:16 UTC, BubuntuClu commented on db/migrate/20210710142607_create_join_table_users_tests.rb
> +      t.index :user_id
твои строки `t.index` надо заменить на то что в комментарии выше.
то как ты хочешь сделать вызывает ошибку дублирования столбцов, так как и то и другое создает столбец.

внешние ключи нужны тут для того, что бы ты не мог вставить сюда значения, которых нет в таблице тестов\пользователей

2021-07-11 04:57 UTC, tagirahmad commented on app/models/user.rb
> +    Test.joins(:users).where(level: level, users: self.id)
Он работает

2021-07-11 10:27 UTC, merged